# 파일 불러오기 (엑셀->CSV)

In [4]:
import pandas as pd
import numpy as np
import glob
import os

## 1. 주민등록인구 파일 불러오기

In [5]:
people_path = r"C:\Users\wodyd\Desktop\파이널프로젝트 자료\고령화율 데이터"
people_files = glob.glob(os.path.join(people_path, "*.xlsx"))

print(f"현재 파일 수: {len(people_files)}")
people_files

현재 파일 수: 6

['C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\고령화율 데이터\\행정구역_시군구_별_주민등록인구_10~11.xlsx',
 'C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\고령화율 데이터\\행정구역_시군구_별_주민등록인구_12~14.xlsx',
 'C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\고령화율 데이터\\행정구역_시군구_별_주민등록인구_15~16.xlsx',
 'C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\고령화율 데이터\\행정구역_시군구_별_주민등록인구_17~19.xlsx',
 'C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\고령화율 데이터\\행정구역_시군구_별_주민등록인구_20~22.xlsx',
 'C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\고령화율 데이터\\행정구역_시군구_별_주민등록인구_23~24.xlsx']

### 1. 주민등록인구 파일 CSV 변환

In [16]:
import pandas as pd
import glob
import os

base_path = r"C:\Users\wodyd\Desktop\파이널프로젝트 자료\고령화율 데이터"

files = glob.glob(
    os.path.join(base_path, "행정구역_시군구_별_주민등록인구_*.csv")
)

dfs = {}

for f in files:
    name = os.path.basename(f)
    df = pd.read_csv(f)
    dfs[name] = df
    print(f"{name} shape:", df.shape)

행정구역_시군구_별_주민등록인구_10~11.csv shape: (1735, 8)
행정구역_시군구_별_주민등록인구_12~14.csv shape: (1837, 11)
행정구역_시군구_별_주민등록인구_15~16.csv shape: (1837, 11)
행정구역_시군구_별_주민등록인구_17~19.csv shape: (1837, 11)
행정구역_시군구_별_주민등록인구_20~22.csv shape: (1837, 11)
행정구역_시군구_별_주민등록인구_23~24.csv shape: (1837, 8)

In [ ]:
import pandas as pd

df10 = pd.read_csv(
    r"C:\Users\wodyd\Desktop\파이널프로젝트 자료\고령화율 데이터\행정구역_시군구_별_주민등록인구_10~11.csv"
)

df12 = pd.read_csv(
    r"C:\Users\wodyd\Desktop\파이널프로젝트 자료\고령화율 데이터\행정구역_시군구_별_주민등록인구_12~14.csv"
)
df13 = pd.read_csv(
    r"C:\Users\wodyd\Desktop\파이널프로젝트 자료\고령화율 데이터\행정구역_시군구_별_주민등록인구_15~16.csv"
)

df14 = pd.read_csv(
    r"C:\Users\wodyd\Desktop\파이널프로젝트 자료\고령화율 데이터\행정구역_시군구_별_주민등록인구_12~14.csv"
)
col = '행정구역(시군구)별'  # 너 컬럼명 그대로

print("10~11 세종 포함?:", df10[col].astype(str).str.contains("세종").any())
print("12~14 세종 포함?:", df12[col].astype(str).str.contains("세종").any())
print("15~16 세종 포함?:", df13[col].astype(str).str.contains("세종").any())
s10 = set(df10[col].dropna().astype(str).str.strip().unique())
s12 = set(df12[col].dropna().astype(str).str.strip().unique())
print("있는 지역:", sorted(s12 - s10))

10~11 세종 포함?: False
12~14 세종 포함?: True
12~14에만 있는 지역: ['세종특별자치시']

In [ ]:
s10 = set(df10[col].dropna().astype(str).str.strip().unique())
s12 = set(df12[col].dropna().astype(str).str.strip().unique())

print("12~14에만 있는 지역:", sorted(s12 - s10)[:50])
print("10~11에만 있는 지역:", sorted(s10 - s12)[:50])

In [12]:
from pandas import concat
concat([df], ignore_index = True)

      행정구역(시군구)별      연령별
0     행정구역(시군구)별      연령별
1             전국        계
2            NaN       0세
3            NaN       1세
4            NaN       2세
...          ...      ...
1832         NaN      96세
1833         NaN      97세
1834         NaN      98세
1835         NaN      99세
1836         NaN  100세 이상

[1837 rows x 2 columns]

In [ ]:
import pandas as pd

path = r"C:\Users\wodyd\Desktop\파이널프로젝트 자료\고령화율 데이터\행정구역_시군구_별_주민등록인구_10~11.csv"
df = pd.read_csv(path)

df.columns

Index(['행정구역(시군구)별', '연령별', '2010.01', '2010.01.1', '2010.01.2', '2011.01',
       '2011.01.1', '2011.01.2'],
      dtype='object')

In [11]:
df = df.filter(['행정구역(시군구)별','연령별','2010.01','2011.01'])
df

      행정구역(시군구)별      연령별
0     행정구역(시군구)별      연령별
1             전국        계
2            NaN       0세
3            NaN       1세
4            NaN       2세
...          ...      ...
1832         NaN      96세
1833         NaN      97세
1834         NaN      98세
1835         NaN      99세
1836         NaN  100세 이상

[1837 rows x 2 columns]

In [ ]:
df = df.concat

## 2. 장기요양 급여실적 파일 불러오기

In [ ]:
ins_path = r"C:\Users\wodyd\Desktop\파이널프로젝트 자료\장기요양보험 지출 데이터"
ins_files = glob.glob(os.path.join(ins_path, "*.xlsx"))

print(f"현재 파일 수: {len(ins_files)}")
ins_files

현재 파일 수: 16

['C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\장기요양보험 지출 데이터\\3-1_장기요양_급여현황_2015.xlsx',
 'C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\장기요양보험 지출 데이터\\3-2_ 장기요양_급여현황_2015.xlsx',
 'C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\장기요양보험 지출 데이터\\장기요양_급여현황_2010.xlsx',
 'C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\장기요양보험 지출 데이터\\장기요양_급여현황_2011.xlsx',
 'C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\장기요양보험 지출 데이터\\장기요양_급여현황_2012.xlsx',
 'C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\장기요양보험 지출 데이터\\장기요양_급여현황_2013.xlsx',
 'C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\장기요양보험 지출 데이터\\장기요양_급여현황_2014.xlsx',
 'C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\장기요양보험 지출 데이터\\장기요양_급여현황_2016.xlsx',
 'C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\장기요양보험 지출 데이터\\장기요양_급여현황_2017.xlsx',
 'C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\장기요양보험 지출 데이터\\장기요양_급여현황_2018.xlsx',
 'C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\장기요양보험 지출 데이터\\장기요양_급여현황_2019.xlsx',
 'C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\장기요양보험 지출 데이터\\장기요양_급여현황_2020.xlsx',
 'C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\장기요양보험 지출 데이터\\장기요양_급여현황_2021.xlsx',
 'C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\장기요양보험 지출 데이터\\장기요양_급여현황_2022.xlsx',
 'C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\장기요양보험 지출 데이터\\장기요양_급여현황_2023.xlsx',
 'C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\장기요양보험 지출 데이터\\장기요양_급여현황_2024.xlsx']

### 2. 장기요양 급여실적 파일 합치기

In [ ]:
ins_list = []
for f in ins_files:
    df1 = pd.read_excel(f)
    ins_list.append(df1)

ins_raw = pd.concat(ins_list, ignore_index=True)
ins_raw.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,제 III편
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 3. 1인당 GRDP 파일 불러오기

In [ ]:
GRPD_path = r"C:\Users\wodyd\Desktop\파이널프로젝트 자료\1인당 GRDP_시도 10~24"
GRPD_files = glob.glob(os.path.join(GRPD_path, "*.xlsx"))

print(f"현재 파일 수: {len(GRPD_files)}")
GRPD_files

현재 파일 수: 1

['C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\1인당 GRDP_시도 10~24\\1인당_GRDP_시도__20260220153413.xlsx']

AttributeError: 'list' object has no attribute 'columns'