# 1. 파일 불러오기 
## 1. 파일 타입 변환

In [193]:
import pandas as pd
import numpy as np
import glob
import os
from hossam import *

from matplotlib import pyplot as plt
from matplotlib import font_manager as fm # 글꼴을 시스템에 등록
import seaborn as sb

In [194]:
pop = pd.read_csv(r"C:\Users\wodyd\Desktop\파이널프로젝트 자료\합본\population.csv")
cpi = pd.read_csv(r"C:\Users\wodyd\Desktop\파이널프로젝트 자료\합본\cpi.csv")
grdp = pd.read_excel(r"C:\Users\wodyd\Desktop\파이널프로젝트 자료\합본\GRDP.xlsx")
ltc = pd.read_excel(r"C:\Users\wodyd\Desktop\파이널프로젝트 자료\합본\ltc_cost.xlsx")

In [195]:
grdp = pd.read_excel(r"C:\Users\wodyd\Desktop\파이널프로젝트 자료\합본\GRDP.xlsx")

grdp.to_csv(r"C:\Users\wodyd\Desktop\파이널프로젝트 자료\합본\GRDP", index=False, encoding='utf-8-sig')

In [196]:
ltc_cost = pd.read_excel(r"C:\Users\wodyd\Desktop\파이널프로젝트 자료\합본\ltc_cost.xlsx")

ltc_cost.to_csv(r"C:\Users\wodyd\Desktop\파이널프로젝트 자료\합본\ltc_cost", index=False, encoding='utf-8-sig')

## 2. 데이터 전처리
### 1. population

In [197]:
second_col = pop.columns[1]
print("두 번째 열 이름:", second_col)

for x in pop[second_col].head(50).tolist():
    print(repr(x))

두 번째 열 이름: 연령별
'연령별'
'계'
'65세'
'66세'
'67세'
'68세'
'69세'
'70세'
'71세'
'72세'
'73세'
'74세'
'75세'
'76세'
'77세'
'78세'
'79세'
'80세'
'81세'
'82세'
'83세'
'84세'
'85세'
'86세'
'87세'
'88세'
'89세'
'90세'
'91세'
'92세'
'93세'
'94세'
'95세'
'96세'
'97세'
'98세'
'99세'
'100세 이상'
'고령화율'
'계'
'65세'
'66세'
'67세'
'68세'
'69세'
'70세'
'71세'
'72세'
'73세'
'74세'

In [198]:
second_col = pop.columns[1]

tmp = pop.copy()
tmp[second_col] = (
    tmp[second_col]
    .astype(str)
    .str.strip()
    .str.replace("\ufeff", "", regex=False)
)

print(tmp[tmp[second_col].str.contains("고령", na=False)].head(30))
print(tmp[tmp[second_col].str.contains("고령", na=False)].shape)

         시도별   연령별         2010         2011         2012         2013  \
38        전국  고령화율   10.6172141  10.91638343  11.28805028  11.78992598
76     서울특별시  고령화율  9.213550409  9.753506189  10.25930002  10.90796487
77     서울특별시  고령인구     10213153     10312835     10250134     10195064
115    부산광역시  고령화율  10.82703787  11.28928155  11.84172085  12.57224384
116    부산광역시  고령인구      3542631      3566560      3549501      3538191
154    대구광역시  고령화율  9.768136637  10.04820326  10.42441905  11.01129965
155    대구광역시  고령인구      2491683      2512071      2508370      2504945
193    인천광역시  고령화율  8.351665194  8.634279833  8.984815035   9.43022566
194    인천광역시  고령인구      2714309      2761122      2804287      2846899
232    광주광역시  고령화율  8.683968508  8.984775199  9.372605034  9.886800616
233    광주광역시  고령인구      1435300      1456308      1465313      1470061
271    대전광역시  고령화율  8.418566467  8.677559318  9.001060437   9.42500367
272    대전광역시  고령인구      1484849      1504317      1517299      1525888
310    울산광역시  고령화율  6.599170868  6.830610545  7.118395303  7.519009171
311    울산광역시  고령인구      1115625      1127337      1136464      1148130
349  세종특별자치시  고령화율            0            0            0   15.1890511
350  세종특별자치시  고령인구            0            0            0       113911
388      경기도  고령화율  8.446391886  8.690863801  9.028182056  9.428848052
389      경기도  고령인구     11484241     11801232     11948596     12107216
427  강원특별자치도  고령화율  14.41291777  14.83938278  15.23830304  15.76889961
428  강원특별자치도  고령인구      1512088      1528790      1535335      1537704
466     충청북도  고령화율  13.00977851  13.19628707  13.44196471   13.7946055
467     충청북도  고령인구      1527943      1550474      1563023      1565670
505     충청남도  고령화율  14.80811299  14.87150564   15.0344558  15.31996991
506     충청남도  고령인구      2039247      2076239      2103129      2029769
544  전북특별자치도  고령화율   15.0076606   15.2300073  15.65062229  16.26921228
545  전북특별자치도  고령인구      1854293      1868745      1873491      1872500
583     전라남도  고령화율  18.01587978  18.30433531  18.67769805  19.24866807
584     전라남도  고령인구      1911991      1916912      1912725      1907945
622     경상북도  고령화율  15.47558596  15.57383695  15.77692221  16.27865779

            2014         2015         2016         2017         2018  \
38   12.27588431  12.75595929  13.19615102  13.59918353  14.25791711
76   11.51485868  12.10568741  12.65544061  13.12201689  13.86165548
77      10143164     10104515     10018537      9930478      9851767
115  13.32820854  14.06135141  14.70922003  15.41913286  16.37248327
116      3526648      3517898      3513361      3496779      3467055
154  11.62927993   12.2415911  12.76795013  13.32118962  14.11202077
155      2501823      2492658      2487823      2484688      2474309
193   9.85691767  10.31124909  10.73754909  11.08383161  11.74916657
194      2882047      2904876      2927195      2944009      2950771
232  10.36199491   10.8755487  11.34728226  11.81028904  12.39811562
233      1473529      1476891      1472802      1469583      1464037
271  9.881793052  10.39641818  10.94719188  11.39007128  12.08549746
272      1533497      1531287      1518024      1514354      1501378
310  7.961292742  8.389249095  8.838175547  9.339174638  10.07300198
311      1157199      1167232      1173568      1171656      1164489
349  14.58619408  12.35808454   10.5149059  9.970237488  9.552327347
350       123802       161716       215418       244939       283198
388  9.813260863   10.1935834  10.57077133  10.86198661   11.4422039
389     12245960     12366711     12536474     12728620     12890445
427  16.24136376  16.61430126  16.94475769  17.24889815  18.13125695
428      1540745      1543640      1549193      1549212      1548078
466  14.17153968   14.5478296  14.87580036  15.20650585  15.88126756
467      1572779      1578531      1583982      1591674      1593903
505  15.68272996   16.0885582   16.4616862   16.7524075  17.17158123
506      2048438      2063050      2078572      2097406      2117685
544   16.7547136  17.30020769  17.89885643  18.36496363  18.98796453
545      1872297      1871018      1868354      1863298      1851694
583  19.69593409  20.18753085   20.5859865   21.0233497  21.58167868
584      1906363      1904220      1906904      1902380      1893444
622  16.83137494  17.37070139  17.80394349  18.32397548  19.12560014

            2019         2020         2021         2022         2023  \
38   14.81901067  15.57555253   16.4827002   17.2384964  18.10377356
76   14.50056562  15.29506985  16.24904781  16.89223123  17.67455116
77       9766288      9733509      9657969      9505926      9424873
115  17.22854503  18.28672623  19.50543874   20.4710001  21.57774161
116      3438259      3411819      3389388      3348874      3316107
154   14.8162765  15.66952105  16.66051967  17.60029331  18.51731785
155      2460382      2436488      2415813      2383858      2362880
193  12.33397701  13.10451305  14.07642334  14.87055592  15.72236692
194      2955916      2956119      2942452      2949150      2969502
232  12.86127445   13.4929374  14.25069784  14.86859374  15.65187409
233      1459832      1456688      1449115      1441636      1429816
271  12.71436968  13.55599694  14.49342612  15.33537476  16.17775829
272      1488725      1474152      1463291      1451272      1445806
310  10.78961816  11.64897035  12.71479782  13.74819374  14.85918957
311      1154786      1147037      1135370      1121100      1110074
349  9.280524219  9.424002711   9.84293223  10.08929502  10.52104573
350       316814       342328       357871       374377       384496
388  11.91621683  12.55624749    13.297618  13.95706428  14.74829052
389     13090648     13250368     13449499     13571450     13596091
427   18.8382512  19.76443325  20.83471709  21.78148519  22.90134059
428      1541693      1540540      1541696      1538660      1535373
466  16.42398642  17.18235253  18.10605767  18.99652933   19.9754274
467      1599155      1599391      1599658      1597097      1594459
505  17.57006901  18.29885675  19.19553249  19.90963062  20.64842035
506      2125797      2122455      2119837      2118638      2122913
544  19.58030713  20.48817423    21.492355  22.35514666  23.27905492
545      1834532      1817302      1802748      1785392      1768229
583  22.00000639   22.7205059  23.61547087  24.36614784  25.23791674
584      1878904      1864712      1850575      1832604      1816707
622   19.8562082  20.72718655  21.85124651  22.83213492  23.88521852

            2024
38   19.05099342
76   18.55852179
77       9384325
115  22.73950733
116      3290964
154  19.73537435
155      2373844
193  16.67014392
194      3000454
232  16.55741161
233      1418241
271  17.06274166
272      1441562
310  16.02172191
311      1103402
349  11.06775141
350       386944
388  15.66456061
389     13635250
427   24.1266299
428      1526243
466  20.96133856
467      1592155
505  21.40995415
506      2130509
544  24.19635568
545      1752921
583  26.17558824
584      1802672
622  24.79867679
(35, 17)

In [199]:
# 컬럼명 간단히 바꾸기
pop.columns = ["region", "age"] + [str(y) for y in range(2010, 2025)]

# 문자열 정리
pop["region"] = pop["region"].astype(str).str.strip().str.replace("\ufeff", "", regex=False)
pop["age"] = pop["age"].astype(str).str.strip().str.replace("\ufeff", "", regex=False)

# 단위행 제거
pop = pop[pop["region"] != "시도별"].copy()

# 전국 제거
pop = pop[pop["region"] != "전국"].copy()

# 고령화율 행만 추출
pop_rate = pop[pop["age"].str.contains("고령", na=False)].copy()

# wide -> long
pop_panel = pop_rate.melt(
    id_vars=["region", "age"],
    value_vars=[str(y) for y in range(2010, 2025)],
    var_name="year",
    value_name="aging_rate"
)

# 타입 정리
pop_panel["year"] = pop_panel["year"].astype(int)
pop_panel["aging_rate"] = pd.to_numeric(pop_panel["aging_rate"], errors="coerce")

# 최종 컬럼
pop_panel = pop_panel[["region", "year", "aging_rate"]]

print(pop_panel.head(20))
print(pop_panel.shape)

     region  year   aging_rate
0     서울특별시  2010        9.214
1     서울특별시  2010 10213153.000
2     부산광역시  2010       10.827
3     부산광역시  2010  3542631.000
4     대구광역시  2010        9.768
5     대구광역시  2010  2491683.000
6     인천광역시  2010        8.352
7     인천광역시  2010  2714309.000
8     광주광역시  2010        8.684
9     광주광역시  2010  1435300.000
10    대전광역시  2010        8.419
11    대전광역시  2010  1484849.000
12    울산광역시  2010        6.599
13    울산광역시  2010  1115625.000
14  세종특별자치시  2010        0.000
15  세종특별자치시  2010        0.000
16      경기도  2010        8.446
17      경기도  2010 11484241.000
18  강원특별자치도  2010       14.413
19  강원특별자치도  2010  1512088.000
(510, 3)

In [200]:
pop_rate = pop[pop["age"].astype(str).str.strip() == "고령화율"].copy()

In [201]:
pop_panel = pop_rate.melt(
    id_vars=["region", "age"],
    value_vars=[str(y) for y in range(2010, 2025)],
    var_name="year",
    value_name="aging_rate"
)

pop_panel["year"] = pop_panel["year"].astype(int)
pop_panel["aging_rate"] = pd.to_numeric(pop_panel["aging_rate"], errors="coerce")
pop_panel = pop_panel[["region", "year", "aging_rate"]]

print(pop_panel.shape)
print(pop_panel.head(20))

(255, 3)
     region  year  aging_rate
0     서울특별시  2010       9.214
1     부산광역시  2010      10.827
2     대구광역시  2010       9.768
3     인천광역시  2010       8.352
4     광주광역시  2010       8.684
5     대전광역시  2010       8.419
6     울산광역시  2010       6.599
7   세종특별자치시  2010       0.000
8       경기도  2010       8.446
9   강원특별자치도  2010      14.413
10     충청북도  2010      13.010
11     충청남도  2010      14.808
12  전북특별자치도  2010      15.008
13     전라남도  2010      18.016
14     경상북도  2010      15.476
15     경상남도  2010      11.661
16  제주특별자치도  2010      11.902
17    서울특별시  2011       9.754
18    부산광역시  2011      11.289
19    대구광역시  2011      10.048

In [202]:
display(pop_panel)

      region  year  aging_rate
0      서울특별시  2010       9.214
1      부산광역시  2010      10.827
2      대구광역시  2010       9.768
3      인천광역시  2010       8.352
4      광주광역시  2010       8.684
..       ...   ...         ...
250  전북특별자치도  2024      24.196
251     전라남도  2024      26.176
252     경상북도  2024      24.799
253     경상남도  2024      20.701
254  제주특별자치도  2024      18.025

[255 rows x 3 columns]

### 2. 소비자물가지수(cpi)

In [203]:
cpi_panel = cpi.copy()
# 컬럼 공백 제거
cpi_panel.columns = cpi_panel.columns.str.strip()

# 컬럼 이름 정리
cpi_panel = cpi_panel.rename(columns={
    cpi_panel.columns[0]: 'year',
    cpi_panel.columns[1]: 'cpi'
})

# 숫자형 변환
cpi_panel['year'] = pd.to_numeric(cpi_panel['year'], errors='coerce')
cpi_panel['cpi'] = pd.to_numeric(cpi_panel['cpi'], errors='coerce')

# 결측 제거
cpi_panel = cpi_panel.dropna()

# 인덱스 정리
cpi_panel = cpi_panel.reset_index(drop=True)

display(cpi_panel)

    year     cpi
0   2010  86.373
1   2011  89.850
2   2012  91.815
3   2013  93.010
4   2014  94.196
5   2015  94.861
6   2016  95.783
7   2017  97.645
8   2018  99.086
9   2019  99.466
10  2020 100.000
11  2021 102.500
12  2022 107.720
13  2023 111.590
14  2024 114.180

### 3. 요양급여비(ltc_cost)

In [204]:
display(ltc_cost)

,시도별,요양급여비,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,전국,요양급여비,2402287301.350,2588192050,2717747764.860,3082993241,3498139433,3981617681,4417672705.000,5093694004.540,6299189004.400,7736306332.880,8882675046.920,10095748015.870,11444191434.270,13192322556.380,14767543612.300
1,서울특별시,요양급여비,387148917.000,421173772,438877148.000,491413932,561236392,635821995,634179711.000,710054863.190,849761350.520,1000208031.140,1093077958.250,1202308296.800,1358025254.800,1570266152.890,1734610900.410
2,부산광역시,요양급여비,144453176.420,139715016,136461429.000,148605470,162650702,178131597,199281812.000,236408708.430,301225727.440,382941479.340,456169508.340,531990551.070,608714959.220,707112639.070,799348835.080
3,대구광역시,요양급여비,95421098.570,107057201,118860211.000,136751605,153572419,173035131,199178981.200,232985068.330,296733888.250,369797981.750,417408562.850,482284984.610,548790874.640,638301980.540,724831990.150
4,인천광역시,요양급여비,136434657.820,146496356,156926662.000,181894533,207948044,236459028,277689314.510,325396288.060,406126647.740,495934215.010,570313674.400,645753511.950,740985315.400,864583119.730,969981451.130
5,광주광역시,요양급여비,73024072.310,73976539,73352038.000,79292610,87829365,99649845,114131306.240,132646356.020,165164511.610,203472076.660,240300793.050,276114977.370,308091616.400,355159138.410,402233768.470
6,대전광역시,요양급여비,77314398.590,81774461,81977722.000,93425377,78594560,117898386,142359314.140,159457479.510,192714242.100,238207772.260,272195546.900,303396588.010,332314647.660,380813786.820,431249415.780
7,울산광역시,요양급여비,31999340.860,33675781,33705813.000,36628762,40150938,44726367,46815377.840,55698787.460,72150889.930,91604564.670,113370243.930,135942338.770,158344275.160,184320126.710,206745993.180
8,세종특별자치시,요양급여비,0.000,0,7539530.000,8339055,10227640,12808423,8234234.850,10232547.250,13886409.060,18762367.660,23981595.310,30385901.790,36047528.260,43012756.700,49027068.060
9,경기도,요양급여비,510304972.230,558480600,534841650.000,664560713,763966329,890674427,1085672378.060,1266807813.810,1573406582.880,1935884606.330,2208597362.870,2486236996.090,2858004526.520,3340874560.170,3792047955.700
10,강원특별자치도,요양급여비,105484247.880,116822620,127217385.000,143271393,165902722,192173094,210319794.150,238736278.510,286880854.060,342275689.980,382424459.970,428965684.450,476071076.790,531042816.650,578387210.960
11,충청북도,요양급여비,83295871.490,92041028,100335786.000,116085347,132261962,152993821,170940535.280,197872302.690,249275051.590,316800900.660,371894584.100,423426688.370,472467914.910,538519859.710,603200375.380
12,충청남도,요양급여비,131774804.490,146469718,145632615.000,167851347,191259844,214650583,228233594.640,262856501.630,332827403.700,417322299.290,482493679.240,548293143.110,615839012.880,698916954.390,773617016.150
13,전북특별자치도,요양급여비,123828733.590,130046752,136652905.000,154064493,170512905,194264301,211811765.570,244474228.610,304241528.260,377906928.890,449334185.680,518158772.470,577871253.130,652748661.620,715763531.820
14,전라남도,요양급여비,136190306.450,146330702,155094032.000,177038459,200102504,228378364,236359639.890,273146070.740,333510920.290,403779847.600,465732144.240,525258785.870,587003444.360,663641982.510,738308968.690
15,경상북도,요양급여비,160831304.060,180809136,198914490.000,229512001,257584048,289807337,314672278.890,365044701.080,450369127.370,553412895.740,633301731.820,742729402.550,836343512.660,950003073.530,1044443431.060
16,경상남도,요양급여비,161266927.250,163856032,170376405.000,195580827,221238640,246949056,260820887.340,300613897.280,375690935.020,477469950.370,580193615.630,680970056.930,781649684.570,913450058.460,1031327977.800
17,제주특별자치도,요양급여비,43514472.490,49466335,50981945.000,58677316,66404856,73195926,76971779.050,81262111.940,95222934.580,110524725.530,121885400.340,133531335.660,147626536.910,159554888.470,172417722.480

In [205]:
# 원본 복사
ltc_panel = ltc_cost.copy()

# 컬럼 공백 제거
ltc_panel.columns = ltc_panel.columns.astype(str).str.strip()

# 첫 컬럼을 지역 컬럼으로 설정
region_col = ltc_panel.columns[0]

# 지역명 공백 제거
ltc_panel[region_col] = ltc_panel[region_col].astype(str).str.strip()

# wide → long 변환
ltc_panel = ltc_panel.melt(
    id_vars=region_col,
    var_name='year',
    value_name='ltc_cost'
)

# 컬럼 이름 변경
ltc_panel.rename(columns={region_col: 'region'}, inplace=True)

# 전국 제거
ltc_panel = ltc_panel[ltc_panel['region'] != '전국']

# 숫자 변환
ltc_panel['year'] = pd.to_numeric(ltc_panel['year'], errors='coerce')

ltc_panel['ltc_cost'] = (
    ltc_panel['ltc_cost']
    .astype(str)
    .str.replace(',', '', regex=False)
)

ltc_panel['ltc_cost'] = pd.to_numeric(ltc_panel['ltc_cost'], errors='coerce')

# 결측 제거
ltc_panel = ltc_panel.dropna(subset=['year','ltc_cost'])

ltc_panel['year'] = ltc_panel['year'].astype(int)

ltc_panel = ltc_panel.reset_index(drop=True)

display(ltc_panel)

      region  year       ltc_cost
0      서울특별시  2010  387148917.000
1      부산광역시  2010  144453176.420
2      대구광역시  2010   95421098.570
3      인천광역시  2010  136434657.820
4      광주광역시  2010   73024072.310
..       ...   ...            ...
250  전북특별자치도  2024  715763531.820
251     전라남도  2024  738308968.690
252     경상북도  2024 1044443431.060
253     경상남도  2024 1031327977.800
254  제주특별자치도  2024  172417722.480

[255 rows x 3 columns]

### 4. grdp

In [206]:
display(grdp)

,시도별,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,전국,27996,29125,30078,31229,32320,34169,35825,37690,38922,39467,39789,42963,45045,46640,49483
1,서울특별시,32407,33740,34682,35553,36635,38911,41359,43731,46547,48248,49165,53373,56094,58829,61215
2,부산광역시,20459,20883,21761,22554,23991,25707,26800,27210,28355,29436,29272,31950,34465,35431,37085
3,대구광역시,17526,18399,19338,20260,21114,22685,23382,24170,24820,25653,25928,27770,29654,30664,31374
4,인천광역시,23871,24103,24508,25177,26559,28376,29864,31198,31688,32272,32292,35388,38065,39104,41187
5,광주광역시,19867,20426,21203,22248,23448,24731,26248,27449,28594,29807,30823,32098,33497,35143,37675
6,대전광역시,20428,21195,21844,22326,23047,24568,26265,27281,28027,29870,31276,32928,34409,36174,38220
7,울산광역시,58224,64781,65248,65650,63793,65408,65031,66786,65897,65486,59529,70889,76234,80821,85194
8,세종특별자치시,0,0,0,59432,67352,53194,46767,44964,41137,40597,40212,42797,42207,43227,44610
9,경기도,25344,26130,27475,29030,30249,32590,34399,37146,38541,38135,38890,41392,42903,43155,46996
10,강원특별자치도,21906,22660,23566,24751,26351,27608,29380,31200,32267,33780,33945,36350,37797,40749,42563
11,충청북도,27817,29495,30712,32148,33496,36656,39848,43254,46002,46777,46462,49519,52252,53827,56328
12,충청남도,41590,44324,44779,46588,47563,49568,51891,55839,56126,54857,56448,62474,64469,64310,67758
13,전북특별자치도,22033,23161,23767,25040,25890,26827,27300,28545,29319,30400,31213,33164,34484,36052,37980
14,전라남도,36825,37545,38225,39463,39322,40834,42473,43582,44086,44535,45339,52489,54179,55892,59177
15,경상북도,34902,35926,36634,38367,40839,40916,41820,43005,43129,42598,42263,44957,46243,48791,52298
16,경상남도,28403,29574,30712,31117,31316,32739,34005,33985,34291,35355,34325,35661,38612,42638,46550
17,제주특별자치도,22034,23704,25205,26186,27766,30275,32389,34134,33673,33545,32404,33861,35999,38570,39914

In [207]:
grdp.columns = [str(c).strip() for c in grdp.columns]

region_col = grdp.columns[0]

grdp[region_col] = grdp[region_col].astype(str).str.strip()

grdp_panel = grdp.melt(
    id_vars=region_col,
    var_name='year',
    value_name='grdp'
)

grdp_panel.rename(columns={region_col: 'region'}, inplace=True)

grdp_panel['region'] = grdp_panel['region'].astype(str).str.strip()
grdp_panel = grdp_panel[grdp_panel['region'] != '전국']

grdp_panel['year'] = pd.to_numeric(grdp_panel['year'], errors='coerce')
grdp_panel['grdp'] = (
    grdp_panel['grdp']
    .astype(str)
    .str.replace(',', '', regex=False)
    .str.strip()
)
grdp_panel['grdp'] = pd.to_numeric(grdp_panel['grdp'], errors='coerce')

grdp_panel = grdp_panel.dropna(subset=['year', 'grdp'])
grdp_panel['year'] = grdp_panel['year'].astype(int)

grdp_panel.head()

  region  year   grdp
1  서울특별시  2010  32407
2  부산광역시  2010  20459
3  대구광역시  2010  17526
4  인천광역시  2010  23871
5  광주광역시  2010  19867

## 3. 패널 데이터
### 1. 데이터 합치기

In [208]:
final_panel = pop_panel.merge(
    grdp_panel,
    on=['region', 'year'],
    how='left'
)

final_panel = final_panel.merge(
    ltc_panel,
    on=['region', 'year'],
    how='left'
)

final_panel = final_panel.merge(
    cpi_panel,
    on='year',
    how='left'
)
display(final_panel)

      region  year  aging_rate   grdp       ltc_cost     cpi
0      서울특별시  2010       9.214  32407  387148917.000  86.373
1      부산광역시  2010      10.827  20459  144453176.420  86.373
2      대구광역시  2010       9.768  17526   95421098.570  86.373
3      인천광역시  2010       8.352  23871  136434657.820  86.373
4      광주광역시  2010       8.684  19867   73024072.310  86.373
..       ...   ...         ...    ...            ...     ...
250  전북특별자치도  2024      24.196  37980  715763531.820 114.180
251     전라남도  2024      26.176  59177  738308968.690 114.180
252     경상북도  2024      24.799  52298 1044443431.060 114.180
253     경상남도  2024      20.701  46550 1031327977.800 114.180
254  제주특별자치도  2024      18.025  39914  172417722.480 114.180

[255 rows x 6 columns]

### 2. post_2017(정책변수) 추가

In [209]:
final_panel['post_2017'] = (final_panel['year'] >= 2017).astype(int)
display(final_panel)

      region  year  aging_rate   grdp       ltc_cost     cpi  post_2017
0      서울특별시  2010       9.214  32407  387148917.000  86.373          0
1      부산광역시  2010      10.827  20459  144453176.420  86.373          0
2      대구광역시  2010       9.768  17526   95421098.570  86.373          0
3      인천광역시  2010       8.352  23871  136434657.820  86.373          0
4      광주광역시  2010       8.684  19867   73024072.310  86.373          0
..       ...   ...         ...    ...            ...     ...        ...
250  전북특별자치도  2024      24.196  37980  715763531.820 114.180          1
251     전라남도  2024      26.176  59177  738308968.690 114.180          1
252     경상북도  2024      24.799  52298 1044443431.060 114.180          1
253     경상남도  2024      20.701  46550 1031327977.800 114.180          1
254  제주특별자치도  2024      18.025  39914  172417722.480 114.180          1

[255 rows x 7 columns]

### 3. 실질요양급여(ltc_real) 추가
- 물가 영향을 제거한 장기요양보험 지출
- ltc_cost와 ltc_real의 값은 다르다
    - 2024년 값은 유지
    - 2010~2020은 ltc_real > ltc_cost

In [211]:
base_cpi = cpi_panel.loc[cpi_panel['year'] == 2024, 'cpi'].iloc[0]

final_panel['ltc_real'] = (
    final_panel['ltc_cost'] * base_cpi / final_panel['cpi']
)
display(final_panel)

,region,year,aging_rate,grdp,ltc_cost,cpi,post_2017,ltc_real
0,서울특별시,2010,9.214,32407,387148917.000,86.373,0,511787981.696
1,부산광역시,2010,10.827,20459,144453176.420,86.373,0,190958559.777
2,대구광역시,2010,9.768,17526,95421098.570,86.373,0,126141051.425
3,인천광역시,2010,8.352,23871,136434657.820,86.373,0,180358552.208
4,광주광역시,2010,8.684,19867,73024072.310,86.373,0,96533506.725
...,...,...,...,...,...,...,...,...
250,전북특별자치도,2024,24.196,37980,715763531.820,114.180,1,715763531.820
251,전라남도,2024,26.176,59177,738308968.690,114.180,1,738308968.690
252,경상북도,2024,24.799,52298,1044443431.060,114.180,1,1044443431.060
253,경상남도,2024,20.701,46550,1031327977.800,114.180,1,1031327977.800
254,제주특별자치도,2024,18.025,39914,172417722.480,114.180,1,172417722.480

### 4. 2010, 2011 세종특별자치도 데이터 제거
- 패널 모델은 대부분 unbalanced panel을 허용
    - 금지    
        - 0으로 채우기
        - 값 대체 하기

In [212]:
final_panel['ltc_real'] = final_panel['ltc_real'].replace(0, np.nan)

final_panel['log_ltc'] = np.log(final_panel['ltc_real'])

final_panel = final_panel.replace([np.inf, -np.inf], np.nan)

final_panel = final_panel.dropna(subset=['log_ltc'])

display(final_panel)

,region,year,aging_rate,grdp,ltc_cost,cpi,post_2017,ltc_real,log_ltc
0,서울특별시,2010,9.214,32407,387148917.000,86.373,0,511787981.696,20.053
1,부산광역시,2010,10.827,20459,144453176.420,86.373,0,190958559.777,19.068
2,대구광역시,2010,9.768,17526,95421098.570,86.373,0,126141051.425,18.653
3,인천광역시,2010,8.352,23871,136434657.820,86.373,0,180358552.208,19.010
4,광주광역시,2010,8.684,19867,73024072.310,86.373,0,96533506.725,18.385
...,...,...,...,...,...,...,...,...,...
250,전북특별자치도,2024,24.196,37980,715763531.820,114.180,1,715763531.820,20.389
251,전라남도,2024,26.176,59177,738308968.690,114.180,1,738308968.690,20.420
252,경상북도,2024,24.799,52298,1044443431.060,114.180,1,1044443431.060,20.767
253,경상남도,2024,20.701,46550,1031327977.800,114.180,1,1031327977.800,20.754
254,제주특별자치도,2024,18.025,39914,172417722.480,114.180,1,172417722.480,18.965

## 3. 기초통계량
### 1. 데이터 정보 파악

In [213]:
print(f"데이터셋 크기: {final_panel.shape}")
print(f"열 개수: {final_panel.shape[1]}")
print(f"행 개수: {final_panel.shape[0]}")
print(final_panel.info())

데이터셋 크기: (253, 9)
열 개수: 9
행 개수: 253
<class 'pandas.core.frame.DataFrame'>
Index: 253 entries, 0 to 254
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   region      253 non-null    object
 1   year        253 non-null    int32
 2   aging_rate  253 non-null    float64
 3   grdp        253 non-null    int64
 4   ltc_cost    253 non-null    float64
 5   cpi         253 non-null    float64
 6   post_2017   253 non-null    int32
 7   ltc_real    253 non-null    float64
 8   log_ltc     253 non-null    float64
dtypes: float64(5), int32(2), int64(1), object(1)
memory usage: 17.8+ KB
None

### 2. 결측치 확인

In [214]:
from pandas import DataFrame

final_panel.isna().sum()

region        0
year          0
aging_rate    0
grdp          0
ltc_cost      0
cpi           0
post_2017     0
ltc_real      0
log_ltc       0
dtype: int64

### 3. 수치형 변수 기술 통계 확인

In [215]:
final_panel[['aging_rate', 'grdp', 'ltc_cost','ltc_real','cpi']].describe().T

,count,mean,std,min,25%,50%,75%,max
aging_rate,253.000,14.816,4.277,0.000,11.629,14.808,17.570,26.176
grdp,253.000,37509.941,13087.004,0.000,27817.000,34682.000,43582.000,85194.000
ltc_cost,253.000,395745551.857,488224261.126,7539530.000,133531335.660,236359639.890,518158772.470,3792047955.700
ltc_real,253.000,441558572.649,515451565.007,9376066.388,163258151.855,274888959.652,577203596.494,3792047955.700
cpi,253.000,98.621,7.550,86.373,93.010,97.645,102.500,114.180

In [216]:
result = hs_stats.describe(final_panel,'aging_rate', 'grdp', 'ltc_cost','ltc_real','cpi')
print(result)

             count  na_count  na_rate          mean           std         min  \
aging_rate 253.000         0    0.000        14.816         4.277       0.000
grdp       253.000         0    0.000     37509.941     13087.004       0.000
ltc_cost   253.000         0    0.000 395745551.857 488224261.126 7539530.000
ltc_real   253.000         0    0.000 441558572.649 515451565.007 9376066.388
cpi        253.000         0    0.000        98.621         7.550      86.373

                     25%           50%           75%            max  \
aging_rate        11.629        14.808        17.570         26.176
grdp           27817.000     34682.000     43582.000      85194.000
ltc_cost   133531335.660 236359639.890 518158772.470 3792047955.700
ltc_real   163258151.855 274888959.652 577203596.494 3792047955.700
cpi               93.010        97.645       102.500        114.180

                     iqr             up           down  outlier_count  \
aging_rate         5.941         26.481          2.718              1
grdp           15765.000      67229.500       4169.500              7
ltc_cost   384627436.810 1095099927.685 -443409819.555             12
ltc_real   413945444.639 1198121763.452 -457660015.103             14
cpi                9.490        116.735         78.775              0

            outlier_rate  skew      dist log_need
aging_rate         0.395 0.204     거의 대칭       낮음
grdp               2.767 0.897  약한 우측 꼬리       중간
ltc_cost           4.743 3.650  극단 우측 꼬리       높음
ltc_real           5.534 3.439  극단 우측 꼬리       높음
cpi                0.000 0.591  약한 우측 꼬리       중간

#### 인사이트
- 데이터 완성도: 결측치 0개 
- 데이터 분포 특성 
    - aging_rate: 로그변환 불필요
    - ltc_cost, ltc_real: 로그변환 필요
    - grdp, cpi: 로그변환 불필요(grdp의 경우 둘 다 많이 쓰긴 하지만, 패널 데이터에서는 그냥 사용)

### 4. 로그 변환

In [217]:
import numpy as np
final_panel['log_ltc'] = np.log(final_panel['ltc_real'])
display(final_panel)

,region,year,aging_rate,grdp,ltc_cost,cpi,post_2017,ltc_real,log_ltc
0,서울특별시,2010,9.214,32407,387148917.000,86.373,0,511787981.696,20.053
1,부산광역시,2010,10.827,20459,144453176.420,86.373,0,190958559.777,19.068
2,대구광역시,2010,9.768,17526,95421098.570,86.373,0,126141051.425,18.653
3,인천광역시,2010,8.352,23871,136434657.820,86.373,0,180358552.208,19.010
4,광주광역시,2010,8.684,19867,73024072.310,86.373,0,96533506.725,18.385
...,...,...,...,...,...,...,...,...,...
250,전북특별자치도,2024,24.196,37980,715763531.820,114.180,1,715763531.820,20.389
251,전라남도,2024,26.176,59177,738308968.690,114.180,1,738308968.690,20.420
252,경상북도,2024,24.799,52298,1044443431.060,114.180,1,1044443431.060,20.767
253,경상남도,2024,20.701,46550,1031327977.800,114.180,1,1031327977.800,20.754
254,제주특별자치도,2024,18.025,39914,172417722.480,114.180,1,172417722.480,18.965

## 3. 상관분석 수행
### 1. 상관분석

In [218]:
final_panel[['aging_rate','grdp','log_ltc']].corr()

            aging_rate  grdp  log_ltc
aging_rate       1.000 0.279    0.502
grdp             0.279 1.000    0.072
log_ltc          0.502 0.072    1.000

### 2. 다중공선성 확인(VIF)

In [219]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
import statsmodels.api as sm
x = final_panel[['aging_rate','grdp','post_2017']]
x = sm.add_constant(x)

vif_dict = {
    col: variance_inflation_factor(x.values, i)
    for i, col in enumerate(x.columns)
}

print(vif_dict)

{'const': 18.51950041860227, 'aging_rate': 1.3192438375708948, 'grdp': 1.169192533263173, 'post_2017': 1.3980651222598401}

#### 인사이트
- 독립변수끼리 비교하였을 때, 다중공선성(VIF)값은 < 5 이므로 진행 ㄱㄱ
- post_2017은 정책 더미 변수이며 동시에 통제변수로 사용

## 4. Pooled OLS(기본 회귀)
### 1. 기본 관계 분석
- 패널 데이터를 일반 회귀처럼 취급하는 모델
- region x year 구조를 무시하고 전체 관측치로 보는 모델
- 패널 분석 진행 순서: Pooled OLS(패널 구조 무시) -> Fixed Effects(지역 고정효과 통제) -> Random Effects(랜덤 효과)
    - 패널 효과가 실제로 존재하는가에 대해 확인하기 위해

- Fixed Effects(지역 고정효과): 서울은 원래 노인이 많아 의료 이용이 높을 수 있다. 이게 '서울 특성'아며 LTC 증가의 원인이 될 수 있다. 그래서 OLS -> Fixed Effects 해서 비교

In [220]:
import statsmodels. formula.api as smf
ols = smf.ols(
    'log_ltc ~ aging_rate + grdp + post_2017',
    data=final_panel
).fit()

print(ols.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                log_ltc   R-squared:                       0.310
Model:                            OLS   Adj. R-squared:                  0.301
Method:                 Least Squares   F-statistic:                     37.21
Date:                    화, 10 3 2026   Prob (F-statistic):           6.67e-20
Time:                        19:24:07   Log-Likelihood:                -326.10
No. Observations:                 253   AIC:                             660.2
Df Residuals:                     249   BIC:                             674.3
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     18.0222      0.239     75.258      0.000      17.551      18.494
aging_rate     0.1019      0.015      6.808      0.000       0.072       0.131
grdp       -1.133e-05   4.61e-06     -2.460      0.015   -2.04e-05   -2.26e-06
post_2017      0.5737      0.132      4.347      0.000       0.314       0.834
==============================================================================
Omnibus:                       13.797   Durbin-Watson:                   2.814
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               32.430
Skew:                           0.140   Prob(JB):                     9.08e-08
Kurtosis:                       4.731   Cond. No.                     1.74e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.74e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

#### 인사이트
- 모델 유의성
- F-statistic: 37.21
- Prob(F-statistic): 6.67e-20
   - --> 설명변수들이 종속변수(log_ltc)에 영향을 주지 않는다. 즉, 모델 전체는 유의하다

--------------------------
- 설명력 (R^2)
- R-squared: 0.310
- Adj, R-squared: 0.301
   - --> 이 모델은 장기요양보험 지출 변동의 약 31%를 설명한다
--------------------------
- 핵심 변수 해석
- coef = 0.1019
- p-value = 0.000
   - --> 고령화율이 1%p 증가하면 장기요양보험 지출은 약 10% 증가한다
--------------------------
- grdp
- coef = -1.133e-05
- p = 0.015
   - --> 유의(5% 수준)
   - --> 그러나 계수가 매우 작다.
   - ---> GRDP 증가가 LTC 지출과 약한 음의 관계를 가진다
        - 해석
            - 경제력 높은 지역 --> 건강 상태 좋음
            - LTC 이용 감소 가능성
--------------------------
- post_2017
- coef = 0.5737(로그 모델이므로 풀어주면 1.77)
- p = 0.000
   - --> 2017년 정책 이후 LTC 지출 약 77% 증가
   - --> 장기요양 등급 개편의 가능성이 있음
--------------------------
- 잔차 정규성
- Prob(JB): 9.08e-08
   - --> 정규성은 약간 깨져 있으나 표본 수(253)이므로 중심극한정리에 의해 큰 문제는 아니다
--------------------------
- Durbin-Watson
- 2.814
   - --> > 2 이므로 약한 음의 자기성관(큰 문제는 아님)